print list of available algorithms in case of errors

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -144,7 +144,9 @@ check_algorithms() {
 	    two_scale)
 		continue ;;
 	    *)
-		echo "Error: unknown algorithm: $a"; exit 1 ;;
+		echo "Error: unknown algorithm: $a";
+		echo "Available algorithms: $available_algorithms";
+		exit 1 ;;
 	esac
     done
 }
