check for installed boost version

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -565,6 +565,62 @@ check_platform() {
 }
 
 #_____________________________________________________________________
+check_boost_version() {
+    checking_msg "boost version"
+
+    _required_boost_major="1"
+    _required_boost_minor="49"
+    _required_boost_patch="0"
+    _check_boost_version_progr_cpp="${BASEDIR}/check_boost_version.cpp"
+    _check_boost_version_progr_exe="${BASEDIR}/check_boost_version.x"
+
+    # clean up
+    rm -f ${_check_boost_version_progr_cpp} ${_check_boost_version_progr_exe}
+
+    cat <<EOF > ${_check_boost_version_progr_cpp}
+#include <boost/version.hpp>
+int main() {
+   int boost_major = BOOST_VERSION / 100000;
+   int boost_minor = BOOST_VERSION / 100 % 1000;
+   int boost_patch = BOOST_VERSION % 100;
+
+   if (boost_major < ${_required_boost_major})
+      return 1;
+   else if (boost_minor < ${_required_boost_minor})
+      return 2;
+   else if (boost_patch < ${_required_boost_patch})
+      return 3;
+   return 0;
+}
+EOF
+    # compile the version check program
+    $CXX -o ${_check_boost_version_progr_exe} ${_check_boost_version_progr_cpp}
+    _error="$?"
+
+    if test "x${_error}" = "x0" ; then
+        # run the version check program
+        ${_check_boost_version_progr_exe}
+        _error="$?"
+        if test "x${_error}" = "x0" ; then
+            result "ok"
+            logmsg "   Boost version ${_required_boost_major}.${_required_boost_minor}.${_required_boost_patch} or higher found."
+        else
+            result "not ok"
+            message "Error: the installed boost version is too old."
+            message "   Please install version ${_required_boost_major}.${_required_boost_minor}.${_required_boost_patch} or higher."
+            rm -f ${_check_boost_version_progr_cpp} ${_check_boost_version_progr_exe}
+            exit 1
+        fi
+    else
+        message "Warning: could not determine boost version because"
+        message "   compilation of the boost test program failed."
+    fi
+
+    # clean up
+    rm -f ${_check_boost_version_progr_cpp} ${_check_boost_version_progr_exe}
+}
+
+#_____________________________________________________________________
 check_boost_test_libs() {
     check_library "libboost_unit_test_framework" "$boost_lib_dir" \
 	"$default_lib_paths"
@@ -1084,6 +1140,7 @@ guess_machine_word_size
 check_platform
 
 check_algorithms
+check_boost_version
 check_boost_test_incl
 check_boost_test_libs
 check_cxx
