replace tabs by spaces (M-x untabify)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -66,22 +66,22 @@ check_library() {
     found_lib=""
 
     for p in ${libdirs}; do
-	for l in ${libs}; do
-	    liblist=`echo $p/$l` # expands wildcard
+        for l in ${libs}; do
+            liblist=`echo $p/$l` # expands wildcard
             for n in ${liblist} ; do
                 if test -f $n ; then
-		    found_dir=$p
+                    found_dir=$p
                     found_lib=$l
-		    break
-		fi
-	    done
-	done
+                    break
+                fi
+            done
+        done
     done
 
     if test "x$found_dir" = "x" || test "x$found_lib" = "x" ; then
-	echo "not found in $libdirs"
+        echo "not found in $libdirs"
     else
-	echo "found in $found_dir"
+        echo "found in $found_dir"
     fi
 }
 
@@ -118,20 +118,20 @@ check_header() {
     found_hdr=""
 
     for p in ${hdrdirs}; do
-	hdrlist=`echo $p/$hdr` # expands wildcard
+        hdrlist=`echo $p/$hdr` # expands wildcard
         for n in ${hdrlist} ; do
             if test -f $n ; then
-		found_dir=$p
+                found_dir=$p
                 found_hdr=$hdr
-		break
-	    fi
-	done
+                break
+            fi
+        done
     done
 
     if test "x$found_dir" = "x" || test "x$found_hdr" = "x" ; then
-	echo "not found in $hdrdirs"
+        echo "not found in $hdrdirs"
     else
-	echo "found in $found_dir"
+        echo "found in $found_dir"
     fi
 }
 
@@ -139,17 +139,17 @@ check_algorithms() {
     algs=`echo $ALGORITHMS | tr ',' ' '`
     ALGORITHMS=""
     for a in ${algs}; do
-	case "$a" in
-	    all)
-		ALGORITHMS="$available_algorithms"; break ;;
-	    two_scale|lattice)
-		ALGORITHMS="$ALGORITHMS $a"
-		continue ;;
-	    *)
-		echo "Error: unknown algorithm: $a";
-		echo "Available algorithms: $available_algorithms";
-		exit 1 ;;
-	esac
+        case "$a" in
+            all)
+                ALGORITHMS="$available_algorithms"; break ;;
+            two_scale|lattice)
+                ALGORITHMS="$ALGORITHMS $a"
+                continue ;;
+            *)
+                echo "Error: unknown algorithm: $a";
+                echo "Available algorithms: $available_algorithms";
+                exit 1 ;;
+        esac
     done
 }
 
@@ -157,15 +157,15 @@ check_boost_libs() {
     check_library "libboost_unit_test_framework" "$boost_lib_dir"
     if test "x$found_lib" = "x" ; then
         echo "Warning: libboost_unit_test_framework must be installed"
-	echo "  to compile and run the tests, see http://www.boost.org"
+        echo "  to compile and run the tests, see http://www.boost.org"
     else
-	BOOSTLIBS_=-lboost_unit_test_framework
-	if [ -z "$boost_lib_dir" ]; then
+        BOOSTLIBS_=-lboost_unit_test_framework
+        if [ -z "$boost_lib_dir" ]; then
             # assume that the linker will look in the default paths
-	    BOOSTLIBS="$BOOSTLIBS_"
-	else
-	    BOOSTLIBS="-L$boost_lib_dir $BOOSTLIBS_"
-	fi
+            BOOSTLIBS="$BOOSTLIBS_"
+        else
+            BOOSTLIBS="-L$boost_lib_dir $BOOSTLIBS_"
+        fi
     fi
 }
 
@@ -173,40 +173,40 @@ check_boost_incl() {
     check_header "boost/test/unit_test.hpp" "$boost_inc_dir"
     if test "x$found_hdr" = "x" ; then
         echo "Warning: boost/test/unit_test.hpp must be installed"
-	echo "  to compile and run the tests, see http://www.boost.org"
+        echo "  to compile and run the tests, see http://www.boost.org"
     else
         # assume that the compiler will look in the default paths
-	if [ -n "$boost_inc_dir" ]; then
-	    CPPFLAGS="$CPPFLAGS -I$boost_inc_dir"
-	fi
+        if [ -n "$boost_inc_dir" ]; then
+            CPPFLAGS="$CPPFLAGS -I$boost_inc_dir"
+        fi
     fi
 }
 
 check_fortran_libs() {
     case "$FC" in
-	gfortran)
-	    FLIBS="-lgfortran -lm" ;;
-	g77|f77)
-	    FLIBS="-lg2c -lm" ;;
+        gfortran)
+            FLIBS="-lgfortran -lm" ;;
+        g77|f77)
+            FLIBS="-lg2c -lm" ;;
     esac
 }
 
 define() {
     # $@: list of extra define statemens
     if [ -n "$@" ]; then
-	echo "define $@"
-	if [ -z "$extra_defines" ]; then
-	    extra_defines="-D$@"
-	else
-	    extra_defines="$extra_defines -D$@"
-	fi
+        echo "define $@"
+        if [ -z "$extra_defines" ]; then
+            extra_defines="-D$@"
+        else
+            extra_defines="$extra_defines -D$@"
+        fi
     fi
 }
 
 enable_defines() {
     if [ -n "$extra_defines" ]; then
-	echo "adding defines $extra_defines to CPPFLAGS"
-	CPPFLAGS="$extra_defines $CPPFLAGS"
+        echo "adding defines $extra_defines to CPPFLAGS"
+        CPPFLAGS="$extra_defines $CPPFLAGS"
     fi
 }
 
@@ -242,30 +242,30 @@ version() {
 
 if test $# -gt 0 ; then
     while test ! "x$1" = "x" ; do
-	case "$1" in
-	    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
-	    *) optarg= ;;
-	esac
+        case "$1" in
+            -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
+            *) optarg= ;;
+        esac
 
-	case $1 in
-	    --enable-colors)         define "COLOR_PRINTOUT" ;;
-	    --enable-debug)          define "DEBUG" ;;
-	    --enable-silent)         define "SILENT" ;;
-	    --enable-verbose)        define "VERBOSE" ;;
-	    --with-algorithms=*)     ALGORITHMS=$optarg ;;
-	    --with-boost-libdir=*)   boost_lib_dir=$optarg ;;
-	    --with-boost-incdir=*)   boost_inc_dir=$optarg ;;
-	    --with-cxx=*)            CXX=$optarg ;;
-	    --with-cxxflags=*)       CXXFLAGS=$optarg ;;
-	    --with-fc=*)             FC=$optarg ;;
-	    --with-fflags=*)         FFLAGS=$optarg ;;
-	    --help|-h)               help; exit 0 ;;
-	    --libext=*)              LIBEXT=$optarg ;;
-	    --make-lib-cmd=*)        MAKELIB=$optarg ;;
-	    --version|-v)            version; exit 0 ;;
-	    *)  echo "Invalid option '$1'. Try $0 --help" ; exit 1 ;;
-	esac
-	shift
+        case $1 in
+            --enable-colors)         define "COLOR_PRINTOUT" ;;
+            --enable-debug)          define "DEBUG" ;;
+            --enable-silent)         define "SILENT" ;;
+            --enable-verbose)        define "VERBOSE" ;;
+            --with-algorithms=*)     ALGORITHMS=$optarg ;;
+            --with-boost-libdir=*)   boost_lib_dir=$optarg ;;
+            --with-boost-incdir=*)   boost_inc_dir=$optarg ;;
+            --with-cxx=*)            CXX=$optarg ;;
+            --with-cxxflags=*)       CXXFLAGS=$optarg ;;
+            --with-fc=*)             FC=$optarg ;;
+            --with-fflags=*)         FFLAGS=$optarg ;;
+            --help|-h)               help; exit 0 ;;
+            --libext=*)              LIBEXT=$optarg ;;
+            --make-lib-cmd=*)        MAKELIB=$optarg ;;
+            --version|-v)            version; exit 0 ;;
+            *)  echo "Invalid option '$1'. Try $0 --help" ; exit 1 ;;
+        esac
+        shift
     done
 fi
 
