check GNU compiler version

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -25,6 +25,7 @@ logfile="$BASEDIR/config.log"
 statusfile="$BASEDIR/config.status"
 sarahconfig="$BASEDIR/config.sarah"
 boostconfig="$BASEDIR/config.boost"
+gppconfig="$BASEDIR/config.g++"
 
 # whether we are in 32-bit or 64-bit environment
 machine_word_size=""
@@ -137,6 +138,7 @@ guess_machine_word_size() {
     esac
 }
 
+#_____________________________________________________________________
 contains() {
     # Check if string $1 contains $2
     if test $# -lt 2 ; then
@@ -153,6 +155,7 @@ contains() {
     return 1 # not found
 }
 
+#_____________________________________________________________________
 contains_not() {
     # Check if string $1 does not contain $2
     if test $# -lt 2 ; then
@@ -729,6 +732,123 @@ check_boost_thread_incl() {
 }
 
 #_____________________________________________________________________
+is_gnu_cpp_compiler() {
+    checking_msg "${CXX} is GNU compiler"
+    _check_gnu_compiler_cpp="${BASEDIR}/check_gnu_compiler.cpp"
+    _check_gnu_compiler_exe="${BASEDIR}/check_gnu_compiler.x"
+    rm -f ${_check_gnu_compiler_cpp} ${_check_gnu_compiler_exe}
+
+    cat <<EOF > ${_check_gnu_compiler_cpp}
+int main() {
+#if defined(__llvm__) || defined(__clang__)
+   return 1;
+#else
+   #ifdef __GNUC__
+      return 0;
+   #else
+      return 1;
+   #endif
+#endif
+}
+EOF
+    $CXX -o ${_check_gnu_compiler_exe} ${_check_gnu_compiler_cpp}
+    _error="$?"
+    if test "x${_error}" = "x0" ; then
+        # run the version check program
+        ${_check_gnu_compiler_exe}
+        _error="$?"
+        if test "x${_error}" = "x0" ; then
+            result "yes"
+            logmsg "   ${CXX} is a GNU compiler"
+            rm -f ${_check_gnu_compiler_cpp} ${_check_gnu_compiler_exe}
+            return "0"
+        else
+            result "no"
+            rm -f ${_check_gnu_compiler_cpp} ${_check_gnu_compiler_exe}
+            return "1"
+        fi
+    else
+        message "Warning: could not determine compiler type of ${CXX} because"
+        message "   compilation of the test program failed."
+    fi
+
+    rm -f ${_check_gnu_compiler_cpp} ${_check_gnu_compiler_exe}
+}
+
+#_____________________________________________________________________
+check_gpp_version() {
+    _required_gpp_major="4"
+    _required_gpp_minor="6"
+    _required_gpp_patch="0"
+    _check_gpp_version_progr_cpp="${BASEDIR}/check_gpp_version.cpp"
+    _check_gpp_version_progr_exe="${BASEDIR}/check_gpp_version.x"
+
+    checking_msg "${CXX} compiler version > ${_required_gpp_major}.${_required_gpp_minor}.${_required_gpp_patch}"
+
+    # clean up
+    rm -f ${_check_gpp_version_progr_cpp} ${_check_gpp_version_progr_exe}
+    rm -f ${gppconfig}
+
+    cat <<EOF > ${_check_gpp_version_progr_cpp}
+#include <fstream>
+int main() {
+   int gpp_major = __GNUC__;
+   int gpp_minor = __GNUC_MINOR__;
+   int gpp_patch = __GNUC_PATCHLEVEL__;
+   int error = 0;
+
+   if (gpp_major < ${_required_gpp_major})
+      error = 1;
+   else if (gpp_minor < ${_required_gpp_minor})
+      error = 2;
+   else if (gpp_patch < ${_required_gpp_patch})
+      error = 3;
+
+   std::ofstream ostr("${gppconfig}");
+   if (ostr.good()) {
+      ostr << gpp_major << '.' << gpp_minor << '.'
+           << gpp_patch;
+   }
+   ostr.close();
+
+   return error;
+}
+EOF
+    # compile the version check program
+    $CXX -o ${_check_gpp_version_progr_exe} ${_check_gpp_version_progr_cpp}
+    _error="$?"
+
+    if test "x${_error}" = "x0" ; then
+        # run the version check program
+        ${_check_gpp_version_progr_exe}
+        _error="$?"
+        gpp_version=""
+        if test -r "${gppconfig}" ; then
+            gpp_version=`cat ${gppconfig}`
+        fi
+        if test "x${_error}" = "x0" ; then
+            result "ok (version ${gpp_version})"
+            logmsg "   Required ${CXX} version: ${_required_gpp_major}.${_required_gpp_minor}.${_required_gpp_patch}"
+            logmsg "   ${CXX} version found: ${gpp_version}"
+        else
+            result "not ok (version ${gpp_version})"
+            message "Error: the installed ${CXX} version is too old."
+            message "   Please install version ${_required_gpp_major}.${_required_gpp_minor}.${_required_gpp_patch} or higher."
+            rm -f ${_check_gpp_version_progr_cpp} ${_check_gpp_version_progr_exe}
+            rm -f ${gppconfig}
+            exit 1
+        fi
+    else
+        message "Warning: could not determine ${CXX} version because"
+        message "   compilation of the ${CXX} test program failed."
+    fi
+
+    # clean up
+    rm -f ${_check_gpp_version_progr_cpp} ${_check_gpp_version_progr_exe}
+    rm -f ${gppconfig}
+}
+
+#_____________________________________________________________________
 check_cxx() {
     checking_msg "C++ compiler $CXX"
     exists_in_path "$CXX"
@@ -738,6 +858,10 @@ check_cxx() {
         exit 1
     else
         result "found $cmd"
+    fi
+    # check that GNU complier version is sufficiently high
+    if is_gnu_cpp_compiler ; then
+        check_gpp_version
     fi
 }
 
