use different exit codes for the different errors

diff --git a/createmodel b/createmodel
--- a/createmodel
+++ b/createmodel
@@ -10,6 +10,12 @@ model_file=""
 name=""
 sarah_model=""
 
+# exit codes
+exit_ok="0"
+exit_syntax_error="1"
+exit_model_dir_exists="2"
+exit_no_default_model="3"
+
 #_____________________________________________________________________
 find_default_model_files() {
     # searches for FlexibleSUSY.m.in files within the model_files/
@@ -46,7 +52,7 @@ EOF
 if test $# -lt 1 ; then
     echo "Error: Too few arguments"
     help
-    exit 1
+    exit ${exit_syntax_error}
 fi
 
 if test $# -gt 0 ; then
@@ -58,11 +64,11 @@ if test $# -gt 0 ; then
 
         case $1 in
             --force|-f)              overwrite="yes" ;;
-            --help|-h)               help; exit 0 ;;
+            --help|-h)               help; exit ${exit_ok} ;;
             --model-file=*)          model_file="$optarg" ;;
             --name=*)                name="$optarg" ;;
             --sarah-model=*)         sarah_model="$optarg" ;;
-            *)  echo "Invalid option '$1'. Try $0 --help" ; exit 1 ;;
+            *)  echo "Invalid option '$1'. Try $0 --help" ; exit ${exit_syntax_error} ;;
         esac
         shift
     done
@@ -71,7 +77,7 @@ fi
 if [ -z "$name" ] ; then
     echo "Error: no model specified!"
     help
-    exit 1
+    exit ${exit_syntax_error}
 fi
 
 sub_model=$(echo $sarah_model | awk -F / '{ if (NF > 1) print $NF }')
@@ -88,7 +94,7 @@ if test -d "$targetdir" -a "x$overwrite" = "xno" ; then
     echo "Error: directory $targetdir already exists!"
     echo "Please chose another model name or use the --force option."
     echo "See ./`basename $0` --help for more information."
-    exit 1
+    exit ${exit_model_dir_exists}
 fi
 
 # check if we provide a FlexibleSUSY model file for the given model
@@ -99,7 +105,7 @@ if [ -n "$model_file" ]; then
         model_file_dir="$model_file_dir/$model_file"
     else
         echo "Error: there is no default model file for the $model_file"
-        exit 1
+        exit ${exit_no_default_model}
     fi
 else
     # if the user has no default model file specified, we check if one
