correcting error message

diff --git a/createmodel b/createmodel
--- a/createmodel
+++ b/createmodel
@@ -3,12 +3,6 @@
 # configure script for FlexibleSUSY
 # Author: Alexander Voigt
 
-if test $# -lt 1 ; then
-    echo "Error: Too few arguments"
-    echo "Usage: ./`basename $0` <model-name>"
-    exit 1
-fi
-
 # directory of this script
 BASEDIR=$(dirname $0)
 overwrite="no"
@@ -48,6 +42,12 @@ Options:
 --help,-h          Print this help message.
 EOF
 }
+
+if test $# -lt 1 ; then
+    echo "Error: Too few arguments"
+    help
+    exit 1
+fi
 
 if test $# -gt 0 ; then
     while test ! "x$1" = "x" ; do
