install-sarah: check for math command

diff --git a/install-sarah b/install-sarah
--- a/install-sarah
+++ b/install-sarah
@@ -154,6 +154,11 @@ if echo "${sarah_version}" | grep -v '[0-9]\+.[0-9]\+.[0-9]\+' > /dev/null 2>&1 
     exit 1
 fi
 
+exists_in_path "math" || {
+    echo "Error: math not found!"
+    echo "   Please install math and put its location in PATH."
+    exit 1
+}
 printf "Checking for SARAH installation ... "
 math -run "If[Needs[\"SARAH\`\"] === \$Failed, Quit[0]]; Quit[1]" > /dev/null 2>&1
 sarah_is_installed="$?"
