much simpler docker use on CI

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -25,19 +25,19 @@ on:
 jobs:
   no-meta:
     strategy:
-       matrix:
-          OS: [macos-10.15, ubuntu-20.04]
-          CXXCOMPILER: [g++, clang++]
+      matrix:
+        OS: [macos-10.15, ubuntu-20.04]
+        CXXCOMPILER: [g++, clang++]
     runs-on: ${{ matrix.OS }}
 
     steps:
       - name: Homebrew
         if: runner.os == 'macOS'
         run: |
-           brew update
-           brew upgrade
-           brew reinstall gcc
-           brew install gsl
+          brew update
+          brew upgrade
+          brew reinstall gcc
+          brew install gsl
 
       - name: Checkout
         uses: actions/checkout@v2
@@ -63,17 +63,17 @@ jobs:
           conan install . --build=missing
 
       - name: Configure
-        run: |
-          ./configure \
-             --with-cxxflags="-std=c++14 -fPIC" \
-             --with-cxx=$CXXCOMPILER \
-             --with-optional-modules=test \
-             --with-loop-libraries=collier,looptools \
-             --with-install-dir=install \
-             --disable-meta
-          make showbuild
         env:
           CXXCOMPILER: ${{ matrix.CXXCOMPILER }}
+        run: |
+          ./configure \
+            --with-cxxflags="-std=c++14 -fPIC" \
+            --with-cxx=$CXXCOMPILER \
+            --with-optional-modules=test \
+            --with-loop-libraries=collier,looptools \
+            --with-install-dir=install \
+            --disable-meta
+          make showbuild
 
       - name: Make
         run: make -j2
@@ -85,23 +85,23 @@ jobs:
         # Makefile doesn't know about FLEXIBLESUSY_LOOP_LIBRARY flag so tests are not
         # re-run on FLEXIBLESUSY_LOOP_LIBRARY change. Every run must clean logs after itself.
         run: |
-           FLEXIBLESUSY_LOOP_LIBRARY=0 make -j2 execute-compiled-tests execute-shell-tests
-           make clean-test-log
+          FLEXIBLESUSY_LOOP_LIBRARY=0 make -j2 execute-compiled-tests execute-shell-tests
+          make clean-test-log
 
       - name: Run compiled and shell script (Collier)
         run: |
-           FLEXIBLESUSY_LOOP_LIBRARY=1 make -j2 execute-compiled-tests execute-shell-tests
-           make clean-test-log
+          FLEXIBLESUSY_LOOP_LIBRARY=1 make -j2 execute-compiled-tests execute-shell-tests
+          make clean-test-log
 
       - name: Run compiled and shell script (LoopTools)
         run: |
-           FLEXIBLESUSY_LOOP_LIBRARY=2 make -j2 execute-compiled-tests execute-shell-tests
-           make clean-test-log
+          FLEXIBLESUSY_LOOP_LIBRARY=2 make -j2 execute-compiled-tests execute-shell-tests
+          make clean-test-log
 
       - name: Run compiled and shell script (fflite)
         run: |
-           FLEXIBLESUSY_LOOP_LIBRARY=3 make -j2 execute-compiled-tests execute-shell-tests
-           make clean-test-log
+          FLEXIBLESUSY_LOOP_LIBRARY=3 make -j2 execute-compiled-tests execute-shell-tests
+          make clean-test-log
 
       - name: Install
         run: make install-src
@@ -113,14 +113,16 @@ jobs:
     # For non PR triggers we check for the name of the repo so that if someone
     # forks FS github doesn't try to run tests on their code.
     if: (!github.event.pull_request && github.repository == 'FlexibleSUSY/FlexibleSUSY') || github.event.pull_request.head.repo.url == 'https://api.github.com/repos/FlexibleSUSY/FlexibleSUSY'
+
     runs-on: ubuntu-20.04
+    container:
+      image: navir/opensuseleap-for-flexiblesusy:0.5.0
 
     strategy:
       matrix:
         CXXCOMPILER: [g++, clang++]
 
     env:
-      IMAGE_VERSION: '0.5.0'
       FORMCALC_VERSION: '9.9'
       MODELS: 'SM THDMII MSSM CMSSM CMSSMCKM MRSSM2 MRSSM2CKM MSSMCPV MSSMNoFV ScalarLeptoquarks LRLR E6SSM NUHMSSMNoFVHimalaya'
 
@@ -130,76 +132,62 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v2
 
-      - name: Pull the docker image
-        run: docker pull navir/opensuseleap-for-flexiblesusy:$IMAGE_VERSION
-
-      - name: Run the image
-        # mount $GITHUB_WORKSPACE as /FlexibleSUSY on the container
-        run: docker run -it -d --name builder -v $GITHUB_WORKSPACE:/FlexibleSUSY navir/opensuseleap-for-flexiblesusy:$IMAGE_VERSION
-
-      - name: Copy Wolfram Engine license to the image
-        run: |
-          docker exec builder bash -c "mkdir /root/.WolframEngine/Licensing && echo $MATHPASS > /root/.WolframEngine/Licensing/mathpass"
-          printf "Checking if wolframscript command is workings... "
-          docker exec builder bash -c 'if [ $(wolframscript -code 1+2) -eq 3 ]; then echo OK; else echo fail && exit 1; fi'
-          printf "Checking if math command is workings... "
-          docker exec builder bash -c '
-              if [[ $(math -run "Print[7 673, $SystemID]; Exit[]" < /dev/null) =~ 4711([^$"\r\n"]*) ]];
-              then
-                echo OK
-              else
-                echo fail
-                exit 1
-              fi
-            '
+      - name: Activate Wolfram Engine
         env:
-          MATHPASS: ${{ secrets.MATHPASS }}
+          MY_MATH_PASS:    ${{ secrets.MY_MATH_PASS }}
+          MY_MAIL_ADDRESS: ${{ secrets.MY_MAIL_ADDRESS }}
+        run: |
+          wolframscript << EOF
+          $MY_MAIL_ADDRESS
+          $MY_MATH_PASS
+          EOF
+          printf "Checking if wolframscript command is workings... "; if [ $(wolframscript -code 1+2) -eq 3 ]; then echo OK; else echo fail && exit 1; fi
+          printf "Checking if math command is workings... "; if [[ $(math -run "Print[7 673, $SystemID]; Exit[]" < /dev/null) =~ 4711([^$"\r\n"]*) ]]; then echo OK; else echo fail && exit 1; fi
 
       - name: Install FormCalc
         run: |
-          docker exec builder bash -c "wget -q -O - http://www.feynarts.de/formcalc/FormCalc-$FORMCALC_VERSION.tar.gz | tar xzf -"
-          docker exec builder bash -c "cd FormCalc-$FORMCALC_VERSION && ./compile"
-          docker exec builder bash -c "echo 'AppendTo[\$Path, \"/FormCalc-$FORMCALC_VERSION\"];' >> /root/.WolframEngine/Kernel/init.m"
+          cd /
+          wget -q -O - http://www.feynarts.de/formcalc/FormCalc-$FORMCALC_VERSION.tar.gz | tar xzf -
+          cd FormCalc-$FORMCALC_VERSION
+          ./compile
+          echo 'AppendTo[\$Path, \"/FormCalc-$FORMCALC_VERSION\"];' >> /root/.WolframEngine/Kernel/init.m
 
       - name: Create models
-        run: docker exec builder bash -c "cd FlexibleSUSY && for m in $MODELS; do ./createmodel --name=\$m; done"
+        run: for m in $MODELS; do ./createmodel --name=$m; done
 
       - name: Configure
-        run: |
-           docker exec builder bash -c "
-               cd /FlexibleSUSY && \
-               ./configure \
-                  --with-cxx=$CXXCOMPILER \
-                  --with-models=$(echo $MODELS| tr ' ' ',') \
-                  --with-loop-libraries=collier,looptools \
-                  --with-looptools-incdir=/LoopTools-$CXXCOMPILER/include \
-                  --with-looptools-libdir=/LoopTools-$CXXCOMPILER/lib64 \
-                  --with-collier-incdir=/COLLIER/include \
-                  --with-collier-libdir=/COLLIER/lib \
-                  --enable-himalaya \
-                  --with-himalaya-incdir=/Himalaya-$CXXCOMPILER/include \
-                  --with-himalaya-libdir=/Himalaya-$CXXCOMPILER/lib64 \
-                  --enable-gm2calc \
-                  --with-gm2calc-incdir=/GM2Calc-$CXXCOMPILER/include \
-                  --with-gm2calc-libdir=/GM2Calc-$CXXCOMPILER/lib64 \
-                  --with-tsil-incdir=/tsil-$CXXCOMPILER \
-                  --with-tsil-libdir=/tsil-$CXXCOMPILER \
-                  --with-optional-modules=test \
-                  --enable-librarylink \
-                  --with-cxxflags=\"-std=c++14 -O2 -fPIC -Wall -Wpedantic -Wfloat-equal -pipe\"
-           "
-           docker exec builder bash -c "cd /FlexibleSUSY && make showbuild"
         env:
           CXXCOMPILER: ${{ matrix.CXXCOMPILER }}
+        run: |
+          ./configure \
+            --with-cxx=$CXXCOMPILER \
+            --with-models=$(echo $MODELS| tr ' ' ',') \
+            --with-loop-libraries=collier,looptools \
+            --with-looptools-incdir=/LoopTools-$CXXCOMPILER/include \
+            --with-looptools-libdir=/LoopTools-$CXXCOMPILER/lib64 \
+            --with-collier-incdir=/COLLIER/include \
+            --with-collier-libdir=/COLLIER/lib \
+            --enable-himalaya \
+            --with-himalaya-incdir=/Himalaya-$CXXCOMPILER/include \
+            --with-himalaya-libdir=/Himalaya-$CXXCOMPILER/lib64 \
+            --enable-gm2calc \
+            --with-gm2calc-incdir=/GM2Calc-$CXXCOMPILER/include \
+            --with-gm2calc-libdir=/GM2Calc-$CXXCOMPILER/lib64 \
+            --with-tsil-incdir=/tsil-$CXXCOMPILER \
+            --with-tsil-libdir=/tsil-$CXXCOMPILER \
+            --with-optional-modules=test \
+            --enable-librarylink \
+            --with-cxxflags="-std=c++14 -O2 -fPIC -Wall -Wpedantic -pipe"
+          make showbuild
 
       - name: Make
-        run: docker exec builder bash -c 'cd FlexibleSUSY && VERBOSE=1 make -j2'
+        run: make -j2
 
       - name: Run Mathematica tests
-        run: docker exec builder bash -c 'cd FlexibleSUSY && VERBOSE=1 make -j2 execute-meta-tests'
+        run: make -j2 execute-meta-tests
 
       - name: Build compiled tests
-        run: docker exec builder bash -c 'cd FlexibleSUSY && VERBOSE=1 make -j2 alltest'
+        run: make -j2 alltest
 
       # Having a single name entry and a bash loop over integers in the run tag would save a
       # little writing but splitting it into multiple entries makes it easier to see on github which loop
@@ -207,47 +195,50 @@ jobs:
       - name: Run compiled and shell script (Softsusy)
         # Makefile doesn't know about FLEXIBLESUSY_LOOP_LIBRARY flag so tests are not
         # re-run on FLEXIBLESUSY_LOOP_LIBRARY change. Every run must clean logs after itself.
-        run: docker exec -e FLEXIBLESUSY_LOOP_LIBRARY=0 -e VERBOSE=1 builder bash -c 'cd FlexibleSUSY && make -j2 execute-compiled-tests execute-shell-tests && make clean-test-log'
+        run: |
+          FLEXIBLESUSY_LOOP_LIBRARY=0 make -j2 execute-compiled-tests execute-shell-tests
+          make clean-test-log
 
       - name: Run compiled and shell script (Collier)
-        run: docker exec -e FLEXIBLESUSY_LOOP_LIBRARY=1 -e VERBOSE=1 builder bash -c 'cd FlexibleSUSY && make -j2 execute-compiled-tests execute-shell-tests && make clean-test-log'
+        run: |
+          FLEXIBLESUSY_LOOP_LIBRARY=1 make -j2 execute-compiled-tests execute-shell-tests
+          make clean-test-log
 
       - name: Run compiled and shell script (LoopTools)
-        run: docker exec -e FLEXIBLESUSY_LOOP_LIBRARY=2 -e VERBOSE=1 builder bash -c 'cd FlexibleSUSY && make -j2 execute-compiled-tests execute-shell-tests && make clean-test-log'
+        run: |
+          FLEXIBLESUSY_LOOP_LIBRARY=2 make -j2 execute-compiled-tests execute-shell-tests
+          make clean-test-log
 
       - name: Run compiled and shell script (fflite)
-        run: docker exec -e FLEXIBLESUSY_LOOP_LIBRARY=3 -e VERBOSE=1 builder bash -c 'cd FlexibleSUSY && make -j2 execute-compiled-tests execute-shell-tests && make clean-test-log'
+        run: |
+          FLEXIBLESUSY_LOOP_LIBRARY=3 make -j2 execute-compiled-tests execute-shell-tests
+          make clean-test-log
 
       - name: Testing pack-SM-src
-        run: |
-          docker exec builder bash -c 'cd FlexibleSUSY && make pack-SM-src'
-          docker exec builder bash -c 'cd FlexibleSUSY && rm -rf models/SM'
-          docker exec builder bash -c 'cd FlexibleSUSY && tar -xf SM.tar.gz'
-          # The dashes '\' are neeeded here even though the previous step with
-          # configure didn't need them. Maybe it has smothething to with
-          # 'run: ' vs 'run: |'?
-          docker exec builder bash -c "
-               cd /FlexibleSUSY &&
-               ./configure \
-                  --with-cxx=$CXXCOMPILER \
-                  --with-models=SM \
-                  --with-loop-libraries=collier,looptools \
-                  --with-looptools-incdir=/LoopTools-$CXXCOMPILER/include \
-                  --with-looptools-libdir=/LoopTools-$CXXCOMPILER/lib64 \
-                  --with-collier-incdir=/COLLIER/include \
-                  --with-collier-libdir=/COLLIER/lib \
-                  --disable-meta \
-                  --with-optional-modules=test
-               "
-          docker exec -e VERBOSE=1 builder bash -c 'cd FlexibleSUSY && make -j2'
-          docker exec -e VERBOSE=1 builder bash -c 'cd FlexibleSUSY && make -j2 execute-meta-tests'
-          docker exec -e VERBOSE=1 builder bash -c 'cd FlexibleSUSY && make -j2 alltest'
-          for i in {0..3}
-          do
-            docker exec -e FLEXIBLESUSY_LOOP_LIBRARY=$i -e VERBOSE=1 builder bash -c 'cd FlexibleSUSY && make -j2 execute-compiled-tests execute-shell-tests && make clean-test-log'
-          done
         env:
           CXXCOMPILER: ${{ matrix.CXXCOMPILER }}
+        run: |
+          make pack-SM-src
+          rm -rf models/SM
+          tar -xf SM.tar.gz
+          ./configure \
+            --with-cxx=$CXXCOMPILER \
+            --with-models=SM \
+            --with-loop-libraries=collier,looptools \
+            --with-looptools-incdir=/LoopTools-$CXXCOMPILER/include \
+            --with-looptools-libdir=/LoopTools-$CXXCOMPILER/lib64 \
+            --with-collier-incdir=/COLLIER/include \
+            --with-collier-libdir=/COLLIER/lib \
+            --disable-meta \
+            --with-optional-modules=test
+          make -j2
+          make -j2 execute-meta-tests
+          make -j2 alltest
+          for i in {0..3}
+          do
+            FLEXIBLESUSY_LOOP_LIBRARY=$i make -j2 execute-compiled-tests execute-shell-tests
+            make clean-test-log
+          done
 
       - name: (Optional) Save logs in case of an error
         uses: actions/upload-artifact@v2
